import React from 'react'
import Head from 'next/head'
import styled from 'styled-components'
import hero_background from '../components/images/background.jpg'
import { Container } from '../styles/GlobalStyle'
import TopHeader from '../components/TopHeader'
import NavBar from '../components/NavBar'
import Hero_Content from '../pages/Hero_Content'


const Hero = styled.div`
  /* background-image: url('${hero_background}');
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover; */
  background: #0C1444;
  width: 100%;
  height: 100vh;
  margin-bottom: -100px;
`

const Hero_Title = styled.div`
  width: 50%;
  text-align: left;
  margin-top: 80px;
`

const Heading = styled.h1`
  color: #ffffff;
`

const SubHeading = styled.h3`
  color: #ffffff;
`

const Button = styled.button`
`

export default function Home() {
  return (
    <>
    <Head>
        <title>Moderntech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Hero>
      <TopHeader/>
      <NavBar />

    <Container>
      
        <Hero_Title>
            <Heading>MODERNTECH HELLO WORLD</Heading>
            <SubHeading>Your Nationwide On-the-Ground Information Technology  Partner.</SubHeading>
          <Button>Contact Us</Button>
        </Hero_Title>

    </Container>

    
    </Hero>
    <Hero_Content/>
    
    </>
   
  )
}
