import React from 'react'
import Head from 'next/head'
import styled from 'styled-components'
import hero_background from '../components/images/background.jpg'
import TopHeader from '../components/TopHeader'
import NavBar from '../components/NavBar'
import Hero_Content from '../pages/Hero_Content'


const Hero = styled.div`
  /* background-image: url('${hero_background}');
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover; */
  background: #0C1444;
  width: 100%;
  height: 100vh;
  margin-bottom: -100px;
`

const Hero_Title = styled.div`
  text-align: left;
  margin-top: 80px;
`

const Heading = styled.h1`
  color: #ffffff;
`

const SubHeading = styled.h3`
  color: #ffffff;
`

const Button = styled.button`
`

const Row = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
`

const Col = styled.div`
  height: 100%;
  width: 50%;
  display: flex;
  position: relative;
`

const PlayBtn = styled.div`
  width: 100%;
  height: 100%;

`

const Circle = styled.div`
  height: 60px;
  width: 60px;
  background-color: #e21f36;
  border-radius: 50%;
  position: absolute;
  top: 30%;
  left: 50%;
  transform: translate(-50%, -30%);
  transition: .5s;
  &:hover{
    box-shadow: 0 0 10px rgba(226, 31, 54, 0.3),
                0 0 20px rgba(226, 31, 54, 0.3),
                0 0 30px rgba(226, 31, 54, 0.3),
                0 0 0 55px rgba(226, 31, 54, 0.1),
                0 0 0 40px rgba(226, 31, 54, 0.1),
                0 0 0 25px rgba(226, 31, 54, 0.1),
                0 0 0 55px rgba(226, 31, 54, 0.1);
    cursor: pointer;
  }
  /* &::before::after{

  } */
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Moderntech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Hero id="home">
      {/* Top Header Page */}
      <TopHeader/>
      {/* NavBar Page */}
      <NavBar />

        <Row>
          <Col>
            <Hero_Title>
                <Heading>MODERNTECH</Heading>
                <SubHeading>Your Nationwide On-the-Ground Information Technology  Partner.</SubHeading>
              <Button>Contact Us</Button>
            </Hero_Title>
          </Col>

          <Col>
              <PlayBtn>
                <Circle></Circle>
              </PlayBtn>
          </Col>
        </Row>
    </Hero>

    {/* Hero Content Page */}
    <Hero_Content/>
    
    </>
   
  )
}
