import React from 'react'
import Hero from '../pages/Hero'
import About from '../pages/about'
import Services from '../pages/Services'
import GlobalStyles from '../styles/GlobalStyle'
import Footer from '../components/Footer'
import Solution from './Solution'
import Partners from './Partners'
import Newsletter from './Newsletter'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Moderntech Computer System Inc.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;900&display=swap" rel="stylesheet" />
      </Head>

        <GlobalStyles />
        <Hero />
        <About/>
        <Services/>
        <Solution />
        <Partners/>
        <Newsletter/>
        <Footer/>
    </>
  )
}
